### ISSUE TITLE
We should explain our builder versioning scheme.

### ISSUE THREAD

**Issue by dwillist** [paketo-buildpacks/builder#24]
There are a lot of assumptions in the `README.md` file about how these artifacts are versioned. 

We should expand on a few points here:
- options for `<BUILDER>`
- how to get a list of all builders (`gcloud container images list-tags gcr.io/paketo-buildpacks/builder`)
- A more useful listing: `cloud container images list-tags gcr.io/paketo-buildpacks/builder --filter base --sort-by=~TAGS --limit 10`
- `gcr.io/paketo-buildpacks/builder:<BUILDER>` is the 'latest' in the `gcr.io/paketo-buildpacks/builder:<BUILDER>-platform-api-latest` line
- `<Version>` is a semantic version.

- Maybe we should a complete list of builders in this repo to avoid the need to run `gcloud` commands.

**Comment by fg-j** [comment]
Builder releases are now located on [base-builder](https://github.com/paketo-buildpacks/base-builder), [full-builder](https://github.com/paketo-buildpacks/full-builder), and [tiny-builder](https://github.com/paketo-buildpacks/tiny-builder) repos.

They are also distributed on Dockerhub at tags that are listed in the READMEs of the respective repos. Closing given that much of the builder release/publishing process has changed since this issue was opened. Please re-open if any concerns remain.
